general:
  splits: /home/joseph/Games/speedrunning/climb/splits.lss
  layout: /home/joseph/Games/speedrunning/climb/layout.ls1l
  comparison: Average Segments
  timing-method: GameTime
  auto-splitter: /home/joseph/Games/speedrunning/climb/auto-splitter/target/wasm32-unknown-unknown/release/auto_splitter.wasm

window:
  always-on-top: true
  transparency: true
  # width: 400
  # height: 800
  # fps: 30

hotkeys:
  split: Digit1
  reset: Digit2
  undo: Digit3
  skip: Digit4
  pause: Digit5
  undo_all_pauses: Digit6
  previous_comparison: Digit7
  next_comparison: Digit8
  toggle_timing_method: Digit9

# connections:
  # twitch: puttheaccesstokenhere

log:
 path: log.txt
 level: info
 clear: true
